# Generated by Django 2.0.6 on 2018-07-02 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sani_optika', '0002_auto_20180702_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image_path',
            new_name='path',
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 2, 18, 26, 24, 590330)),
        ),
    ]
