# Generated by Django 2.0.6 on 2018-07-02 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sani_optika', '0004_auto_20180702_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 2, 18, 27, 45, 320067)),
        ),
    ]
