# Generated by Django 2.0.7 on 2018-07-03 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sani_optika', '0006_auto_20180702_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='user',
        ),
        migrations.AddField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sani_optika.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 3, 8, 29, 33, 807167)),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sani_optika.Product'),
        ),
    ]
