# Generated by Django 2.0.7 on 2018-07-03 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sani_optika', '0007_auto_20180703_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
