# Generated by Django 2.0.7 on 2018-07-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sani_optika', '0008_auto_20180703_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
