# Generated by Django 2.0.7 on 2018-07-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sani_optika', '0009_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
