# Generated by Django 2.0.6 on 2018-07-03 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sani_optika', '0013_auto_20180703_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationslot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sani_optika.User'),
        ),
    ]
