# Generated by Django 2.0.6 on 2018-07-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sani_optika', '0015_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sani_optika.Product')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sani_optika.User')),
            ],
        ),
    ]
